### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by diegorodriguesvieira** [TwistedScorpio/OTHire#133]
```
[New LWP 29661]
[New LWP 29662]
[New LWP 29660]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./otserv --log-file output.txt error.txt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000005043be in CreatureEvent::executeOnKill (this=0x7fb684718790,
    creature=creature@entry=0x7fb68644ea70,
    target=target@entry=0x7fb6851e7cd0, lastHit=lastHit@entry=true)
    at creatureevent.cpp:345
345                     uint32_t targetId = env->addThing(target);
(gdb) bt
#0  0x00000000005043be in CreatureEvent::executeOnKill (this=0x7fb684718790,
    creature=creature@entry=0x7fb68644ea70,
    target=target@entry=0x7fb6851e7cd0, lastHit=lastHit@entry=true)
    at creatureevent.cpp:345
#1  0x00000000004e6fca in Creature::onKillEvent (this=0x7fb68644ea70,
    target=0x7fb6851e7cd0, lastHit=<optimized out>) at creature.cpp:1708
#2  0x00000000004e9eba in Creature::onDie (this=0x7fb6851e7cd0)
    at creature.cpp:796
#3  0x00000000004628ee in Game::checkCreatures (this=0x7cdf80 <g_game>)
    at game.cpp:3894
#4  0x000000000049b703 in operator() (this=0x7fb6859b23a8)
    at /usr/include/boost/function/function_template.hpp:767
#5  operator() (this=0x7fb6859b23a0) at tasks.h:44
#6  Dispatcher::dispatcherThread (p=0x7cdec0 <g_dispatcher>) at tasks.cpp:87
#7  0x00007fb6900d0aea in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#8  0x00007fb68fc2b064 in start_thread (arg=0x7fb68c4a7700)
    at pthread_create.c:309
#9  0x00007fb68edd762d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)
```

**Comment by diegorodriguesvieira** [comment]
@peonso

**Comment by diegorodriguesvieira** [comment]
https://github.com/opentibia/server/commit/ae3493ad9386a3b4aed34a3bbacd1180d2ccba7d

**Comment by diegorodriguesvieira** [comment]
I got the Iryont code, I'm testing now...

**Comment by diegorodriguesvieira** [comment]
https://github.com/TwistedScorpio/OTHire/pull/129/commits/d13bc3215f56cfa6f95ef7a838c5ea372c730d99
