### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by diegorodriguesvieira** [TwistedScorpio/OTHire#141]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./otserv --log-file output.txt error.txt'.
Program terminated with signal SIGBUS, Bus error.
#0  cancel (ec=<synthetic pointer>, impl=..., this=0x10005ffd12462005)
    at /usr/include/boost/asio/detail/deadline_timer_service.hpp:108
108	    std::size_t count = scheduler_.cancel_timer(timer_queue_, impl.timer_data);
(gdb) bt
#0  cancel (ec=<synthetic pointer>, impl=..., this=0x10005ffd12462005)
    at /usr/include/boost/asio/detail/deadline_timer_service.hpp:108
#1  expires_at (ec=<synthetic pointer>, expiry_time=..., impl=..., this=0x10005ffd12462005)
    at /usr/include/boost/asio/detail/deadline_timer_service.hpp:144
#2  expires_from_now (ec=<synthetic pointer>, expiry_time=..., impl=..., this=0x10005ffd12462005)
    at /usr/include/boost/asio/detail/deadline_timer_service.hpp:161
#3  expires_from_now (ec=<synthetic pointer>, expiry_time=..., impl=..., this=0x10005ffd12461fdd)
    at /usr/include/boost/asio/deadline_timer_service.hpp:129
#4  boost::asio::basic_deadline_timer<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime>, boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > >::expires_from_now (this=this@entry=0x24ac9e8, expiry_time=...) at /usr/include/boost/asio/basic_deadline_timer.hpp:414
#5  0x00000000004c7600 in Connection::parsePacket (this=0x24a8dd0, error=...) at connection.cpp:369
#6  0x00000000004c90d1 in call<boost::shared_ptr<Connection>, boost::system::error_code const> (b1=..., u=..., 
    this=0x7ffe46395f78) at /usr/include/boost/bind/mem_fn_template.hpp:156
#7  operator()<boost::shared_ptr<Connection> > (a1=..., u=..., this=0x7ffe46395f78)
    at /usr/include/boost/bind/mem_fn_template.hpp:171
#8  operator()<boost::_mfi::mf1<void, Connection, const boost::system::error_code&>, boost::_bi::list2<const boost::system::error_code&, long unsigned int const&> > (a=<synthetic pointer>, f=..., this=0x7ffe46395f88)
    at /usr/include/boost/bind/bind.hpp:313
#9  operator()<boost::system::error_code, long unsigned int> (a2=@0x7ffe46395f70: 9752, a1=..., this=0x7ffe46395f78)
    at /usr/include/boost/bind/bind_template.hpp:102
#10 boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void---Type <return> to continue, or q <return> to quit---
```

**Comment by diegorodriguesvieira** [comment]
It only happened once in my OT and it never happened again...looks an error on hardware...
