### ISSUE TITLE
Monsters casting spells through walls crash

### ISSUE THREAD

**Issue by diegorodriguesvieira** [TwistedScorpio/OTHire#85]
Crash when I was walking on cave...

```!c++
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb5c31b40 (LWP 27546)]
0x081120b7 in Tile::hasProperty (this=0x0, prop=prop@entry=BLOCKSOLID, checkSolidForItems=checkSolidForItems@entry=false) at tile.cpp:46
46        if(ground && ground->hasProperty(prop)){
(gdb) bt
#0  0x081120b7 in Tile::hasProperty (this=0x0, prop=prop@entry=BLOCKSOLID, checkSolidForItems=checkSolidForItems@entry=false) at tile.cpp:46
Python Exception <class 'IndexError'> list index out of range:
#1  0x080d8ecc in AreaCombat::getList (this=0xb3b1e6b0, centerPos=..., targetPos=..., list=empty std::list) at combat.cpp:1259
#2  0x080d9372 in Combat::CombatFunc (caster=caster@entry=0xb3adc7b8, pos=..., area=0xb3b1e6b0, params=...,
    func=0x80d7450 <Combat::CombatHealthFunc(Creature*, Creature*, CombatParams const&, void*)>, data=0xb5c30ff8) at combat.cpp:806
#3  0x080d9843 in Combat::doCombat (this=0xb3b4ddd8, caster=0xb3adc7b8, pos=...) at combat.cpp:917
#4  0x080ba397 in CombatSpell::castSpell (this=0xb3b41580, creature=0xb3adc7b8) at spells.cpp:424
#5  0x080ba567 in CombatSpell::castSpell (this=0xb3b41580, creature=0xb3adc7b8, target=0xb32706b8) at spells.cpp:459
#6  0x08077734 in Monster::doAttacking (this=0xb3adc7b8, interval=1000) at monster.cpp:813
#7  0x08129fa2 in Creature::onAttacking (this=0xb3adc7b8, interval=1000) at creature.cpp:274
#8  0x0812eb55 in Creature::onThink (this=this@entry=0xb3adc7b8, interval=interval@entry=1000) at creature.cpp:263
#9  0x08079663 in Monster::onThink (this=0xb3adc7b8, interval=1000) at monster.cpp:734
#10 0x080acea5 in Game::checkCreatures (this=0x81fdf40 <g_game>) at game.cpp:3764
#11 0x080e10e1 in operator() (this=0xb31c5020) at /usr/include/boost/function/function_template.hpp:767
#12 operator() (this=0xb31c5018) at tasks.h:44
#13 Dispatcher::dispatcherThread (p=0x81fdec0 <g_dispatcher>) at tasks.cpp:87
#14 0xb7b72681 in ?? () from /usr/lib/i386-linux-gnu/libboost_thread.so.1.54.0
#15 0xb7acef72 in start_thread (arg=0xb5c31b40) at pthread_create.c:312
#16 0xb775ef8e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
```

**Comment by FioletowyAka** [comment]
Btw. does someone know how to enable loot messages?

**Comment by diegorodriguesvieira** [comment]
@FioletowyAka 
**Change this line:**
https://github.com/TwistedScorpio/OTHire/blob/master/data/creaturescripts/scripts/login.lua#L15

```!lua
sendLootMessage = true -- enable//disable
```

**Comment by peonso** [comment]
fixed https://github.com/TwistedScorpio/OTHire/commit/0e1deb49242432a9b0223f27b7f46f4d66f43d75
